### ISSUE TITLE
Line width not changing

### ISSUE THREAD

**Issue by c-whelan** [ardata-fr/mschart#36] opened 2018-10-16 23:59 UTC
Using `chart_data_line_width()` to alter line width of a line chart does not seem to be working:

```
library(mschart)
library(tidyverse)

ms_linechart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  print(preview = TRUE)

ms_linechart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_data_line_width(1) %>%
  print(preview = TRUE)
```
Both examples produce the same chart (with the default line width of 3.75). 

It does work for scatter plots:

```
ms_scatterchart(data = iris, x = "Sepal.Length", y = "Sepal.Width", group = "Species") %>%
  chart_settings(scatterstyle="line") %>%
  chart_data_line_width(1) %>%
  print(preview = TRUE)
```

Thanks for investigating!

(Love the package btw!)

**Comment by bcondron** [comment] 2018-10-19 04:33
This is a duplicate of #34 and should be closed.

It has been fixed in the github version of the package, which can be installed using devtools.

**Comment by c-whelan** [comment] 2018-10-19 17:16
My apologies. Confirmed it is fixed in Github version. Will close.

**Closed** 2018-10-19 17:17 UTC
