### ISSUE TITLE
using other characters than Basic Latin

### ISSUE THREAD

**Issue by pegazpegaz** [ardata-fr/mschart#23] opened 2018-04-25 14:58 UTC
Hello,

I got problems using other characters than Basic Latin ones in PowerPoint charts. 
When I add any of them anywhere into fresh PowerPoint into chart and then export it with print() I got error when opening presentation in PowerPoint. It just say's it's broken. 
This could be fixed by unpacking file and changing "�" character.

I figured out, that problem is caused by mschart not officer, because you can add any characters in text fields with standard officer commands (like ph_with_text).

You could easily reproduce it with the code below.

```
library(officer)
library(mschart)
barchart <- ms_barchart(data = browser_data, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")
barchart <- chart_labels(barchart,
                         title = "©")
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")
```

Best regards,
Peter

**Comment by davidgohel** [comment] 2018-04-26 10:02
Hi,

The `sessionInfo()` is missing in your issue. I can't reproduce the issue so maybe you are on windows?

Can you try with the following code?

```
library(officer)
library(mschart)
barchart <- ms_barchart(data = browser_data, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")
barchart <- chart_labels(barchart,
                         title = enc2utf8("©"))
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")
```

**Comment by pegazpegaz** [comment] 2018-04-26 17:14
Yes, I'm working on windows machine.
Following code gives the same results.

Here's my session info:

`R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mschart_0.2.3 officer_0.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12        digest_0.6.15       R.methodsS3_1.7.1   cellranger_1.1.0    R6_2.2.2           
 [6] magrittr_1.5        writexl_0.2         zip_1.0.0           uuid_0.1-2          data.table_1.10.4-3
[11] R.oo_1.21.0         R.utils_2.6.0       xml2_1.2.0          tools_3.4.1         compiler_3.4.1     
[16] base64enc_0.1-3     htmltools_0.3.6    `

**Comment by adibsul** [comment] 2018-05-30 12:15
I also got problems when I use other characters than Basic Latin.

`library(officer)
library(mschart)
barchart <- ms_barchart(data = browser_data, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")

doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")`

I get error when I open "Presentation.pptx". This happens when there are words in "browser" column which contain swedish letters (äÄ, åÅ, öÖ).

`R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Swedish_Sweden.1252  LC_CTYPE=Swedish_Sweden.1252    LC_MONETARY=Swedish_Sweden.1252 LC_NUMERIC=C                    LC_TIME=Swedish_Sweden.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] mschart_0.2.3     magrittr_1.5      gdtools_0.1.7     officer_0.3.0     rvg_0.1.8         ggplot2_2.2.1     r2excel_1.0.0     reshape2_1.4.2    bindrcpp_0.2     
[10] xlsx_0.5.7        xlsxjars_0.6.1    rJava_0.9-9       purrr_0.2.4       SKIunderlag_0.1.4 dplyr_0.7.4       foreign_0.8-69    haven_1.1.1.9000 

loaded via a namespace (and not attached):
 [1] zip_1.0.0           Rcpp_0.12.16        cellranger_1.1.0    pillar_1.2.2        compiler_3.4.3      git2r_0.19.0        plyr_1.8.4          bindr_0.1          
 [9] base64enc_0.1-3     R.methodsS3_1.7.1   R.utils_2.6.0       forcats_0.3.0       tools_3.4.3         uuid_0.1-2          digest_0.6.12       memoise_1.1.0      
[17] tibble_1.4.2        gtable_0.2.0        pkgconfig_2.0.1     rlang_0.2.0         writexl_1.0         curl_3.0            yaml_2.1.14         xml2_1.2.0         
[25] withr_2.1.2         stringr_1.3.0       httr_1.3.1          hms_0.4.2           devtools_1.13.3     grid_3.4.3          data.table_1.10.4-3 glue_1.2.0         
[33] R6_2.2.2            readr_1.1.1         htmltools_0.3.6     scales_0.5.0        assertthat_0.2.0    colorspace_1.3-2    labeling_0.3        stringi_1.1.7      
[41] lazyeval_0.2.1      munsell_0.4.3       R.oo_1.22.0   `

Thank you for your help in this matter.

**Comment by davidgohel** [comment] 2018-06-11 10:14
It is fixed now. Thanks, that was an issue with a `cat` that was not using UTF8 encoding...


This is the code I used:

```
library(magrittr)
library(mschart)
library(officer)

dat <- browser_data
dat[dat$browser %in% "Chrome", "browser"] <- "äÄ åÅ öÖ"
barchart <- ms_barchart(data = dat, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")
barchart <- chart_labels(barchart, title = "©")
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")
```

```
#> C:/Users/dgohe/AppData/Local/Temp/RtmpGm5PPw/Presentation.pptx
```
The produced file is here: [Presentation.pptx](https://github.com/ardata-fr/mschart/files/2089528/Presentation.pptx)


```
sessionInfo()
```

```
#> R version 3.5.0 (2018-04-23)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252   
#> [3] LC_MONETARY=French_France.1252 LC_NUMERIC=C                  
#> [5] LC_TIME=French_France.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] mschart_0.2.3     magrittr_1.5      officer_0.3.1.001
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_0.12.17      crayon_1.3.4      digest_0.6.15    
#>  [4] rprojroot_1.3-2   cellranger_1.1.0  R6_2.2.2         
#>  [7] backports_1.1.2   evaluate_0.10.1   writexl_1.0      
#> [10] zip_1.0.0         stringi_1.1.7     uuid_0.1-2       
#> [13] data.table_1.11.2 fs_1.2.2          xml2_1.2.0       
#> [16] rmarkdown_1.9     tools_3.5.0       stringr_1.3.1    
#> [19] yaml_2.1.19       compiler_3.5.0    base64enc_0.1-3  
#> [22] htmltools_0.3.6   knitr_1.20
```

**Closed by davidgohel** 2018-06-11 10:14 UTC

**Comment by aidusgs** [comment] 2018-08-30 16:48
I copied your code and I'm afraid it still produced a broken "Presentation.pptx".

This is my session info:

```R version 3.5.0 (2018-04-23)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5  officer_0.3.2 mschart_0.2.3

loaded via a namespace (and not attached):
 [1] compiler_3.5.0    R6_2.2.2          htmltools_0.3.6   tools_3.5.0      
 [5] base64enc_0.1-3   Rcpp_0.12.18      uuid_0.1-2        cellranger_1.1.0 
 [9] xml2_1.2.0        writexl_1.0       data.table_1.11.4 digest_0.6.16    
[13] zip_1.0.0
```
Thank you for any help on this matter.

**Comment by davidgohel** [comment] 2018-08-31 13:53
That's because you didn't install github version but cran version. This bug fix is not yet on cran.

**Comment by aidusgs** [comment] 2018-08-31 14:09
Thank you for this information. Do you know when it will be on cran?

**Comment by davidgohel** [comment] 2018-09-03 13:42
no sorry, I usually wait for at least 2/3 bug fixes before submitting to cran a new release.

**Comment by lichaoping** [comment] 2019-08-24 13:32
I tested the following code on my machine. I can't the PPT file. It told me there is an error.

library(magrittr)
library(mschart)
library(officer)

dat <- browser_data
dat[dat$browser %in% "Chrome", "browser"] <- "äÄ åÅ öÖ"
barchart <- ms_barchart(data = dat, 
                        x = "browser", 
                        y = "value", 
                        group = "serie")
barchart <- chart_labels(barchart, title = "©")
doc <- read_pptx()
doc <- add_slide(doc, layout = "Title and Content", master = "Office Theme")
doc <- ph_with_chart(doc, chart = barchart)
print(doc, target = "Presentation.pptx")

sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

Random number generation:
 RNG:     Mersenne-Twister 
 Normal:  Inversion 
 Sample:  Rounding 
 
locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mschart_0.2.4 magrittr_1.5  officer_0.3.5
